//Array de objetos, simulación de base de datos de productos
//Entrega final, agregar en cada producto la propiedad "stock", completar las propiedades faltantes.
//Editar las imágenes grandes de las cards de detalle y cambiar color de fondo de las imágenes chicas.
const products = [

    {
        id: 1,
        nombre: "Shampoo Sólido Cabello Graso",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "graso",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 450,
        presentacion: "50gr",
        imagen: "./Images/shampoo-cabello-graso.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 2, 
        nombre: "Shampoo Sólido Cabello Seco", 
        tipoProducto: "cuidado del cabello", 
        tipoPiel: "no disponible", 
        tipoCabello: "seco",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 450, 
        presentacion: "50gr",
        imagen: "./Images/shampoo-cabello-seco.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Si tu pelo tiene tendencia a ser muy seco, quebradizo o con frizz o si fue sometido a tratamientos agresivos como tinturas, decoloraciones o uso constante de la planchita, nuestro shampoo con aceite de almendras dulces, formulado con mayor porcentaje de aceite y agregado de elastina ayudará a mantenerlo fuerte e hidratado. Con aroma a jazmín, rosas y benjuí.",
        modoUso: "Frotá la pastilla entre tus manos o sobre el cabello mojado hasta generar la cantidad de espuma deseada. Masajeá el cuero cabelludo durante algunos minutos y luego enjuagá. Si tu cabello es muy seco, dejar algo de producto ayudará a mantenerlo hidratado. No olvides colocar el shampoo en un lugar seco después de usarlo para maximizar su duración.",
        inci: "SCI (Sodium Cocoyl Isethionate), Hidrolato de Rosas (Rosa Damascena Flower Water), Aceite de Almendras Dulces (Prunus Amygdalus Dulcis Oil), Manteca de Karité (Butyrospermum Parkii Butter), Elastina Hidrolizada (Hydrolized Elastin, Phenoxyethanol / Ethylhexylglycerin), Proteína de Seda Hidrolizada (Hydrolized Silk Protein, Phenoxyethanol / Ethylhexylglycerin), Geogard®221 (Dehydroacetic Acid, Benzyl Alcohol), Vitamina E (Tocopherol Acetate), AE de Ylang Ylang (Cananga Odorata Oil), Esencia de Sándalo.",
    },

    {
        id: 3, 
        nombre: "Acondicionador Sólido para Todo Tipo de Cabello",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 500,
        presentacion: "50gr",
        imagen: "./Images/acondicionador-solido.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 4, 
        nombre: "Aceite Capilar de Jojoba", 
        tipoProducto: "cuidado del cabello", 
        tipoPiel: "no disponible", 
        tipoCabello: "graso", 
        usos: "nutricion", 
        zeroWaste: "NO",
        precio: 700, 
        presentacion: "60ml",
        imagen: "./Images/aceite-jojoba.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 5,
        nombre: "Aceite Capilar de Almendras Dulces",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "normal",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 500,
        presentacion: "60ml",
        imagen: "./Images/aceite-almendras-dulces.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 6,
        nombre: "Blend de Aceites Capilares Palta y Coco",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "seco",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "60ml",
        imagen: "./Images/aceite-palta-coco.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 7,
        nombre: "Blend de Aceites para el Cabello",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 700,
        presentacion: "60ml",
        imagen: "./Images/blend-aceites.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 8,
        nombre: "Limpiador Facial Sólido Pieles Grasas",
        tipoProducto: "cuidado facial",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 400,
        presentacion: "50gr",
        imagen: "./Images/limpiador-facial-pieles-grasas.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 9,
        nombre: "Limpiador Facial Sólido Pieles Secas",
        tipoProducto: "cuidado facial",
        tipoPiel: "seca",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 400,
        presentacion: "50gr",
        imagen: "./Images/limpiador-facial-pieles-secas.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 10,
        nombre: "Limpiador Facial Sólido Pieles Sensibles",
        tipoProducto: "cuidado facial",
        tipoPiel: "sensible",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 400,
        presentacion: "50gr",
        imagen: "./Images/limpiador-facial-pieles-sensibles.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 11,
        nombre: "Limpiador Facial Pieles Normales",
        tipoProducto:"cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 800,
        presentacion: "125ml",
        imagen: "./Images/limpiador-facial-pieles-normales.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 12,
        nombre: "Agua de Rosas",
        tipoProducto: "cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "60ml",
        imagen: "./Images/agua-rosas.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 13,
        nombre: "Agua de Lavanda",
        tipoProducto: "cuidado facial",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "60ml",
        imagen: "./Images/agua-lavanda.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 14,
        nombre: "Sérum Facial con Vitamina C",
        tipoProducto: "cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "15cc",
        imagen: "./Images/serum-facial.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 15,
        nombre: "Body Lotion Pieles Grasas",
        tipoProducto: "cuidado corporal",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 1000,
        presentacion: "250cc",
        imagen: "./Images/body-lotion-piel-grasa.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 16,
        nombre: "Body Lotion Pieles Secas",
        tipoProducto: "cuidado corporal",
        tipoPiel: "seca",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 1000,
        presentacion: "250cc",
        imagen: "./Images/body-lotion-piel-seca.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 17,
        nombre: "Body Lotion Pieles Maduras",
        tipoProducto: "cuidado corporal",
        tipoPiel: "madura",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 1000,
        presentacion: "250cc",
        imagen: "./Images/body-lotion-piel-madura.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 18,
        nombre: "Arcilla Verde",
        tipoProducto: "cuidado facial",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 550,
        presentacion: "50gr",
        imagen: "./Images/arcilla-verde.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 19,
        nombre: "Arcilla Blanca",
        tipoProducto: "cuidado facial",
        tipoPiel: "normal",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 550,
        presentacion: "50gr",
        imagen: "./Images/arcilla-blanca.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 20,
        nombre: "Arcilla Roja",
        tipoProducto: "cuidado facial",
        tipoPiel: "seca",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 550,
        presentacion: "50gr",
        imagen: "./Images/arcilla-roja.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 21,
        nombre: "Arcilla Detox",
        tipoProducto: "cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "50gr",
        imagen: "./Images/arcilla-detox.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 22,
        nombre: "Cofia de Seda",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "otros",
        zeroWaste: "SI",
        precio: 500,
        presentacion: "x 1",
        imagen: "./Images/cofia-seda.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },

    {
        id: 23,
        nombre: "Sujetador de Cabello de Seda",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "otros",
        zeroWaste: "SI",
        precio: 200,
        presentacion: "x 1",
        imagen: "./Images/sujetador-seda.png",
        imagenDetalle: "./Images/shampoo-solido-seco-grande.png",
        detalle: "Completar para la entrega final.",
        modoUso: "Completar para la entrega final.",
        inci: "Completar para la entrega final.",
    },
]

//Exportar función getProductInfo, simulación de API
export const getProductInfo = () => {
    //Retorna promesa de respuesta a la petición de datos de productos
    //Las Promise son objetos predefinidos del entorno de JS
    /*"resolve" es el parámetro de la función que se pasa luego al bloque de código que se ejecuta
    al recibir la respuesta, en este caso con el método .then de promesa resuelta correctamente. Se
    escribe dentro de un setTimeOut para simular el tiempo que demora en procesarse una petición
    real*/
    /*El array de objetos "products" se pasa como argumento de "resolve", es decir, la base de datos
    de productos es la respuesta a la petición del usuario.*/
    //El tiempo está en milisegundos (3000ms = 3s)
    /*La promesa resuelta como error también se puede trabajar como segundo argumento dentro del
    método then(), sin usar el método catch()*/
    //Método finally() siempre se ejecuta, usar con useState para crear un spinner (clase 5, 1 hora 40 minutos)
    return new Promise (resolve => {
        setTimeout(() => {
            resolve(products)
        }, 3000)
    })
}
