const products = [

    {
        id: 1,
        nombre: "Shampoo Sólido Cabello Graso",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "graso",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 450,
        presentacion: "50gr",
        imagen: "./Images/shampoo-cabello-graso.png",
    },

    {
        id: 2, 
        nombre: "Shampoo Sólido Cabello Seco", 
        tipoProducto: "cuidado del cabello", 
        tipoPiel: "no disponible", 
        tipoCabello: "seco",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 450, 
        presentacion: "50gr",
        imagen: "./Images/shampoo-cabello-seco.png",
    },

    {
        id: 3, 
        nombre: "Acondicionador Sólido para Todo Tipo de Cabello",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 500,
        presentacion: "50gr",
        imagen: "./Images/acondicionador-solido.png",
    },

    {
        id: 4, 
        nombre: "Aceite Capilar de Jojoba", 
        tipoProducto: "cuidado del cabello", 
        tipoPiel: "no disponible", 
        tipoCabello: "graso", 
        usos: "nutricion", 
        zeroWaste: "NO",
        precio: 700, 
        presentacion: "60ml",
        imagen: "./Images/aceite-jojoba.png",
    },

    {
        id: 5,
        nombre: "Aceite Capilar de Almendras Dulces",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "normal",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 500,
        presentacion: "60ml",
        imagen: "./Images/aceite-almendras-dulces.png",
    },

    {
        id: 6,
        nombre: "Blend de Aceites Capilares Palta y Coco",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "seco",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "60ml",
        imagen: "./Images/aceite-palta-coco.png",
    },

    {
        id: 7,
        nombre: "Blend de Aceites para el Cabello",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 700,
        presentacion: "60ml",
        imagen: "./Images/blend-aceites.png",
    },

    {
        id: 8,
        nombre: "Limpiador Facial Sólido Pieles Grasas",
        tipoProducto: "cuidado facial",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 400,
        presentacion: "50gr",
        imagen: "./Images/limpiador-facial-pieles-grasas.png",
    },

    {
        id: 9,
        nombre: "Limpiador Facial Sólido Pieles Secas",
        tipoProducto: "cuidado facial",
        tipoPiel: "seca",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 400,
        presentacion: "50gr",
        imagen: "./Images/limpiador-facial-pieles-secas.png",
    },

    {
        id: 10,
        nombre: "Limpiador Facial Sólido Pieles Sensibles",
        tipoProducto: "cuidado facial",
        tipoPiel: "sensible",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "SI",
        precio: 400,
        presentacion: "50gr",
        imagen: "./Images/limpiador-facial-pieles-sensibles.png",
    },

    {
        id: 11,
        nombre: "Limpiador Facial Pieles Normales",
        tipoProducto:"cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 800,
        presentacion: "125ml",
        imagen: "./Images/limpiador-facial-pieles-normales.png",
    },

    {
        id: 12,
        nombre: "Agua de Rosas",
        tipoProducto: "cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "60ml",
        imagen: "./Images/agua-rosas.png",
    },

    {
        id: 13,
        nombre: "Agua de Lavanda",
        tipoProducto: "cuidado facial",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "60ml",
        imagen: "./Images/agua-lavanda.png",
    },

    {
        id: 14,
        nombre: "Sérum Facial con Vitamina C",
        tipoProducto: "cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "nutricion",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "15cc",
        imagen: "./Images/serum-facial.png",
    },

    {
        id: 15,
        nombre: "Body Lotion Pieles Grasas",
        tipoProducto: "cuidado corporal",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 1000,
        presentacion: "250cc",
        imagen: "./Images/body-lotion-piel-grasa.png",
    },

    {
        id: 16,
        nombre: "Body Lotion Pieles Secas",
        tipoProducto: "cuidado corporal",
        tipoPiel: "seca",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 1000,
        presentacion: "250cc",
        imagen: "./Images/body-lotion-piel-seca.png",
    },

    {
        id: 17,
        nombre: "Body Lotion Pieles Maduras",
        tipoProducto: "cuidado corporal",
        tipoPiel: "madura",
        tipoCabello: "no disponible",
        usos: "hidratacion",
        zeroWaste: "NO",
        precio: 1000,
        presentacion: "250cc",
        imagen: "./Images/body-lotion-piel-madura.png",
    },

    {
        id: 18,
        nombre: "Arcilla Verde",
        tipoProducto: "cuidado facial",
        tipoPiel: "grasa",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 550,
        presentacion: "50gr",
        imagen: "./Images/arcilla-verde.png",
    },

    {
        id: 19,
        nombre: "Arcilla Blanca",
        tipoProducto: "cuidado facial",
        tipoPiel: "normal",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 550,
        presentacion: "50gr",
        imagen: "./Images/arcilla-blanca.png",
    },

    {
        id: 20,
        nombre: "Arcilla Roja",
        tipoProducto: "cuidado facial",
        tipoPiel: "seca",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 550,
        presentacion: "50gr",
        imagen: "./Images/arcilla-roja.png",
    },

    {
        id: 21,
        nombre: "Arcilla Detox",
        tipoProducto: "cuidado facial",
        tipoPiel: "todos",
        tipoCabello: "no disponible",
        usos: "limpieza",
        zeroWaste: "NO",
        precio: 600,
        presentacion: "50gr",
        imagen: "./Images/arcilla-detox.png",
    },

    {
        id: 22,
        nombre: "Cofia de Seda",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "otros",
        zeroWaste: "SI",
        precio: 500,
        presentacion: "x 1",
        imagen: "./Images/cofia-seda.png",
    },

    {
        id: 23,
        nombre: "Sujetador de Cabello de Seda",
        tipoProducto: "cuidado del cabello",
        tipoPiel: "no disponible",
        tipoCabello: "todos",
        usos: "otros",
        zeroWaste: "SI",
        precio: 200,
        presentacion: "x 1",
        imagen: "./Images/sujetador-seda.png",
    },
]

export const getProductInfo = () => {
    return new Promise (resolve => {
        setTimeout(() => {
            resolve(products)
        }, 3000)
    })
}
